replicaCount: 1

image:
  repository: ghcr.io/ericafenyo/geo-trails-api
  tag: latest
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr-token

namespace: ""

env:
  secretRef: geo-trails-api-env
  nodeEnv: production
  port: 3000

service:
  type: ClusterIP
  port: 80

ingress:
  host: ""
  entrypoints: web,websecure

probes:
  readiness:
    path: /
    initialDelaySeconds: 10
    periodSeconds: 10
  liveness:
    path: /
    initialDelaySeconds: 20
    periodSeconds: 20
