apiVersion: v1
kind: Secret
data:
    .dockerconfigjson: ENC[AES256_GCM,data:9BK1nCKjNirlxFoq0PT5MORcIp4zfDAz25NxdisUzpvXuYFft4x7y+UTXIq9FEnyGXWUlOQZNnvdKpjkYEASgvZzbBGw3uZRLnB3HimJQIMU4VGa5C0bnk/pg6Q1kIm1Ryp/QZfmL2aOXPzWyC2e30F2zeO8l4PL29EBpLecnZHNalscVmBU+P0+lAnFJFst+nhi+R+NteG2r6WnxBwvVsYbGyFqFY6HJJJJcnEcME8TfMqSC3faIFAjWT/FpE+2GGOhe5dfdg6hVZ10R2es7ZlJTJPyPUvFBObOj5kKdcwXP4VwNBBfdx6XIspqHQpIjffIMqElZKtPe/V7tbNcX4Nc/GpG8NwTLdrcsb9M/3q42rolqgH4Yg==,iv:bI/Q4FCrHF6+JE/BIKUjcao51a0THrYWmodPis4/YtE=,tag:r3IUwvcH66eCjb2jEhaS6A==,type:str]
metadata:
    name: ghcr-token
    namespace: gta-dev
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age1tryrjtpz890ms9p0t0j4g36e8slteaunk92qnxf95puqz58aqe4qqgd4ea
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOQzZaQ0prV3Rzb1hlR2ZI
            UEFTS25HUUVJYTY3M1dEeEUwelVuYzcvK0VnCkRHSHJYWTEzRFE1czZMR1IxbWRL
            SFJyQzJ6bEV0YjdsdXZsQnVhamhRLzgKLS0tIGhJM3NVZDZvM3JWakE4b1hlZVl4
            Z2I5T3Zrbm9aeG0zalViR0lyVGh2cnMKvAdOdmuGjYT/Uz8f8Bv4JnLv5ekSBgM2
            AbGAAmVLKrgdbawfQGcoIJm0TpPaUZw4cGWmDL7ophyZCATdFryprQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T21:02:29Z"
    mac: ENC[AES256_GCM,data:qcnvafKGDISyQu9kIreN1NJDruriXUWDPAW0ivfnaW4xn5V8NIzvTFd5kyKB8rkZ2wlhj+sfLaRTHaG+XwgIJqMyw4P23LJkb0cOmegddGExz0mJRctf034oB0cVmxmmG5vXBgj4K5JCRxnKQaX3Qy0+Hc0QFn+ClWqqTPkYqAE=,iv:GJyXp8G5Iu8tqG5E9QhPAkKlgq4GKVaSdtqwM5SqKIY=,tag:yriJJIMALkxYcLh+hd4VKQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
