apiVersion: v1
kind: Secret
data:
    .dockerconfigjson: ENC[AES256_GCM,data:tfVCOKomEdBFCSLWJGR3ug7H4V8IQrA/xTyVv9NrnlUVMRf7KxJlZ5/FEnqcXZXvlvX+W75qgL5sBWc0ha+3GzOui9dP9hR9CzCLRQ69APKlp8p1KiEqN99ixklKLVxjdUocleVKIvkP4Zu9fwOH+T4sVumlcBtgIBHh1n8WvxWKIzYjd84OZY/qwISKQ1fhK0jCyX8SdFke2kmgOto3R6pJVtuAiuxjKWIADiF0l0Gx9EdwIPbdSM5dAC3OTbdrP/sbVoo5Quz3oS/Tx+kAePHpsPBZZSfklzyJ+Rr7qJpzTHPCwnVI9PSW8gJZOHRzSHUaxg4kM4eSqb+D+uqvsDT5d1d8bniOTGJNkT/z7ClNQO3ayt9NzA==,iv:Y32wClhhIVFloBqGx8m7a6ek3Xf1xwr/BWmYU1vzTmI=,tag:v6KPv6JReDYJwHMkBVQ5qQ==,type:str]
metadata:
    name: ghcr-token
    namespace: gta-dev
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age1tryrjtpz890ms9p0t0j4g36e8slteaunk92qnxf95puqz58aqe4qqgd4ea
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvaGNJVEdpdTJJaDdWQlJP
            WDNZaG82SWx3Rmp1dnZ0M0w1Q0FTZkNydkFBCk1JWUE3VDVPdURSaFA1b2lLbDAw
            R291NkZnRXBLT3UxM25iQUlTRHMzbmMKLS0tIEVIUEFqV0RxVDBkV25FdVduTEpv
            L05yR09XNERFcnBFRzluaXkzOWRGNXcKG1CzVf5vH+3i0GE7SaDMuVZP0RC2FXPh
            zCDyilW1mK/AvajbIdR+hjGN1O+VFpdiXY2tct2DbFPv+zm7Gjky5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T22:48:42Z"
    mac: ENC[AES256_GCM,data:BwiaI0amcxWKKJTMaA6Lz7PWG95YWKKvjkA9sWcQBSUCfJox9BpAarnSxv8AvalLbqyV9JFHSUL42/o/lxKt5ZBJaqQFu5hacSxL7jkyMaU/MckVy9o7b/eHwqLIxv8R8irksmbvsO30c8GjLhkA2hF3vokir7T/He5r1FjBUDA=,iv:w5Lr3ZNqomCdJFbaf5cVXMDX7urwMkjo0eJ49f+JDCQ=,tag:OzCJe/V8MBqOfatlQqFtbg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
