apiVersion: v1
kind: Secret
metadata:
    name: api-env
    namespace: gta-dev
type: Opaque
stringData:
    PORT: ENC[AES256_GCM,data:PxOFFg==,iv:LQsEqOIRqTcQp60Zk5RND49nFXlw+BsJfOj8zGaeSP4=,tag:jgmxqnQv/5z0k0aR+Ybt+g==,type:str]
    MONGO_URL: ENC[AES256_GCM,data:yCkDln42NJcFToBwCciyNkEOPqUXca6wkTEcol8xhuvNHi2vvbjabp01LGFfAL5GaiZeorpDbBA9C2VfCY2lVaE7rXMInSUpUnv5/6QQtpsLe53QCEYUgKIEU/2x8Q==,iv:gj2mrBD8mlHf9b+fiXW0PhxjCTWbJPGdAZc8cSsbNhc=,tag:OiFobmN14xfsDzzabfALoQ==,type:str]
    JWT_AUDIENCE: ENC[AES256_GCM,data:nOnR59KhpwzF6Bwa24IZwaNC2w==,iv:2jD6Nihl0PhoV1SiFgTKROLTXpCVa0PO7IrMpD4QMqI=,tag:Acj0AGznHh+CVvn3BdgeTQ==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:d40Y670xd3SB,iv:NO+3NZiFnpqpv977ofAQOj1rQtUnBzTFSOPLjpzDOSQ=,tag:LbmKf9b38G0XZ3+Tr+kmpw==,type:str]
    MAILER_HOST: ENC[AES256_GCM,data:LWekUoUNXNArzq5q5JnjtqpC/POCcHjf,iv:uTPyaNIpVYy7plYLmu7mvCoq4L8wlmfLjE7wANFUXyg=,tag:9vcamXh3CKfQ5akMAH+SOw==,type:str]
    MAILER_PORT: ENC[AES256_GCM,data:H7sqtQ==,iv:lYC+KEe7Exg53sM+lz+pWH4wckpYTaiFkFKM1B5ur1o=,tag:9b9pBxvMTcKFAkDrcV+z1g==,type:str]
    MAILER_USERNAME: ENC[AES256_GCM,data:R0uHgNVfMKW7u+rvilA=,iv:VQSgGQpfFph644FfK3Oyq4ltF6LGql15oV6Stm4X+JE=,tag:L/URMbP4xAnTYSvb9r2VKg==,type:str]
    MAILER_PASSWORD: ENC[AES256_GCM,data:MRpPwQOUBFuevru/kpo=,iv:Ix6MEK3pqJf8cr/WqXeQ5wk1Lhh5hR+1RklcQxz9yic=,tag:W3h19yioysnJuT1BklYSdA==,type:str]
    OTP_SECRET: ENC[AES256_GCM,data:xq0PSaafFufU,iv:VDCR9BbH14T3x+DkWSzyR0uw5l3nqb5F37Phfp80RtQ=,tag:yN189PQvC26C/hDQ2Ck9Ew==,type:str]
    OAUTH_ISSUER_BASEURL: ENC[AES256_GCM,data:UyYEVetxtrqh+uOSJEqUowYvfL/pL7pP45oDg5i7EV6jvSE=,iv:rZBZUGOsYjlGjxzDeBg4KjnDrms1p5G71g/7uw3DBFI=,tag:maPiw1IdQsqZHBsmTAT7mg==,type:str]
    OAUTH_DOMAIN: ENC[AES256_GCM,data:ak5CggPaAjFhJ7B8nO4aDFN3A0UAbUD4Ef47,iv:uCxUw1ryVXrOHBAtXhGttnCrQoq5oIa4ZtC11hWXbJE=,tag:FaHmq0Fjg0B+OAyz1b5pJw==,type:str]
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:Uz26AkrsTksVodclOxvkLxC/iyUFmcz+UC8lNhvzEBk=,iv:lMXHOib6jZcGSTu1TW0kXmypO4dO8kIWZQn4wsN0SGw=,tag:x+uXnq/eR83qsCI+souDeA==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:zDdPmP0FoKOGWnASrjCkZ8tSF00ZOUmqXvVaDZUx2bMpivlCYnSECjd5M8k6g/v8ytxgOsGGTCPElu962VXUDg==,iv:+ZlAwz8sCToxup0MA4Eh8KcjEvS+BejHbUo7wMPY12g=,tag:ayktPchKPmjfQibcqtlgYw==,type:str]
    OAUTH_AUDIENCE: ENC[AES256_GCM,data:AEdLAbqKd1fnT6M9MEYqrqTjI7zrY2aMpE50C0yWtQ==,iv:gYEMyIY2+kI932/YVAE5JC3h2+UR16CSGoRohDr4V2U=,tag:U0Ob+6psVUDAo+a0MJzG8Q==,type:str]
    OAUTH_SCOPE: ENC[AES256_GCM,data:V+eiEeVtfu89sA0Qz5LItac5N/4=,iv:XX6q+/KoQf4WCdsJCxMBB4NP3iF29Mk1/GMeBZrXAcI=,tag:H18OsJ0bwviRb9N2mGslcw==,type:str]
    OAUTH_TOKEN_SIGNING_ALGORITHM: ENC[AES256_GCM,data:5WU6tcY=,iv:mxaVpRSnsCYAxHx54yk6oxwkR4cG9kihv0YV0kdbJoE=,tag:SQrdruOD3LvACS2r+8iEwQ==,type:str]
sops:
    age:
        - recipient: age1vgjwad52rqd29uyukq4nzsqp09z6e40a6zr7enhrv8psd4wnwu3qlfc803
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RUFoazVkaHFVY1VTQTlJ
            UkpzUFF0M2dEUEVtUzBKZUhtU1hJZ2FWOTA4CkhYRVNzb3VCUURDR2hnWC9NelB0
            ajh1QklNV0d0Z0h5RkpjV2pFb2ZUL1UKLS0tIGJxTjRJNHhJMmVKcmZoaXExMjR2
            Zm9xa0tFMlFNRUhLMUkwM0Z1emNWaDgKe3sk0B/FwoW0uPeGgAw7wzCJExTyxNwx
            Hpn/aHJHeBL404Sox5XJCgAfHiyUtT9e8b6Tk44boC3Hb7qZY0wrzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-21T11:35:08Z"
    mac: ENC[AES256_GCM,data:PPaablAq23C/Vwbzed0onk+f2JFEZkTLhM/4xNjFj03k20PpHQ1QJ0HRwe68Y0BVBBjFbywytWV9YzQHP0IdWxJopulXfXdqEQvSVQEuMR1A/TFVauRR9pS25lesMZWyZxe9/ImYRuZYGvvI0dQaIcH38PAu10yHkTD1ZfMdx5k=,iv:1pJKprqxFvsku0mwbz00cUZj1qTpAiSMZE25nxvd5v0=,tag:nNEB//G132LTHUOInpk6kQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
