apiVersion: v1
kind: Secret
data:
    .dockerconfigjson: ENC[AES256_GCM,data:LbiFodVTHsYwjBBbQcRTs2hsc9zt5Nqr7LIp3tRKQSYNVrG0epUULCcbDMFzw5d3rXpgp0T3FOPYudJz7zx+SKcMaUaXrwcs9Qik4+zNc7WZlODiIyn4evapE76a8VaW4pIB9ME9KRriz89+TP8V8ZbWJk9TMNGBS3ijlIPmQVVm+0/RzN0ZugJbkosHHHit4xBCdU3C3KmbC8o8L3ydO8inFWcFCu8pkGVdkDdkWS6+veAv8BwylIFVrunNLLf6JQHgY6PgQxen2VU9rvxDKlSqsoPgZqxcNrcTwLmNmLl7B4JCWrAe4L9dJHUeK64FD5xkIbzBzmvOgkduSEM/LoWZiH1cUjT2lshsp4uPOhnzesr1E5bVjA==,iv:ZotCK+LdSnkC+1C3W6THg8ckYwoPIHQvHpDVff/pCSU=,tag:75whw7555EaZI5WVrDL6HQ==,type:str]
metadata:
    name: ghcr-token
    namespace: gta-dev
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age1vgjwad52rqd29uyukq4nzsqp09z6e40a6zr7enhrv8psd4wnwu3qlfc803
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBblBIUlhEMHdJOFBpanhH
            RVpjTmdmWFRkclo2WnV4b0t4UFVOVXFDTTM0CkZkMzRsTjhBSlZqNnBzWVRTclFu
            Z3g5UjVrY2xNNCtOVDF0VC9PVk9NTmsKLS0tIEpKSjNGQlg0NnhQOGVQVjczdWZk
            RmFxd3BhMUF4ZEdhQ3AvOEZYRisrS2sKvEQA+sWbvam8gkutUQ5dCT5D/QEslyED
            /oNVbt/yCSsMYaqSiVESoxQfl1dgrh1466Yi28BTARPmuArkbMdwZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-21T11:35:08Z"
    mac: ENC[AES256_GCM,data:L4rAG0Nkj+Gf5+hKslSAvjW6nVzYsnNNjuNq5H2tn1EP8dvTafUM12ntHY6ALJW92lI+X2Fq9m8qAnrCas5jEflKRw9kdUlggmemzAgO9Fig0ozY5Bczg2UvmaypFASKHNdPCfUSHAnm3F0PDyx2dGpXi+/FnraxartDmDb4zKc=,iv:8XGOTdicWFWbcwCPTQmPoovN00zZ2o0wp2J/EPxr84Q=,tag:VzXAZ45l2iqrCMjkwHCiaw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
