apiVersion: v1
kind: Secret
metadata:
    name: api-env
    namespace: gta-dev
type: Opaque
stringData:
    PORT: ENC[AES256_GCM,data:7NRvrg==,iv:XjV57Cn6CctGaxQMVyMSHjnaQIQ/BfV60J9YtsKUmog=,tag:OsD1CdvIKfK9UNsj8xQsfw==,type:str]
    MONGO_URL: ENC[AES256_GCM,data:jG+7HyLvR/qv9DzCzut4sCaB8zjJSg4foa2Y/C0MoB4ibgWFHtS75PykNS96MhHwGfeyPIvPmWyvM7NwlTDjKJl4sTuTFkqeHXEZAuhNQ/KWmZzJW9qcD3w4cmohihd9,iv:r/SFVHr/1IlTj80BGsMOHQJ7OFyqKwcVc+7l9s3Ybns=,tag:u5cIoOBOPYJ4vq2ZQ8X1mw==,type:str]
    JWT_AUDIENCE: ENC[AES256_GCM,data:74ewIENWWand/Pe44AbyGH4GRQ==,iv:LNzIqgjJvlqMTXPoTTbK2fMARleuA9qk3DZ5R89lIoo=,tag:ZVRjwQMVNfSCLwgae5RKMQ==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:G9bViu9E3dou,iv:5KYBMbTyk9qqq2k+TBRqGbZydGw9kek1XxdOqx5akuI=,tag:DTLR8sHvZciz4cnyClXZKw==,type:str]
    MAILER_HOST: ENC[AES256_GCM,data:Sm1azff6W9tvwb3kUZ1ceINC4teu/x2F,iv:Q36xO9t+FzESZl/n0p3+jtHejq0wZur8He0j0VPoE+U=,tag:F4XsXt7y9ynM1rskPpODow==,type:str]
    MAILER_PORT: ENC[AES256_GCM,data:zVRXPA==,iv:q7dV+dQ8TUuG0iH2eXhRTOREmRWgVjRZebKeJIFuabQ=,tag:iWwpl4j7qp9wDjftMcROZQ==,type:str]
    MAILER_USERNAME: ENC[AES256_GCM,data:+cQ0LAvGM4kuPDIwliI=,iv:i9U2nk8eR4jDG0hW82QbHjoQ0AAjY5IKAwy+MhKIbTA=,tag:R8Gsg4UhHgfBW+CCGKGKHQ==,type:str]
    MAILER_PASSWORD: ENC[AES256_GCM,data:sdWVZ4PvGEC0zo7oQnY=,iv:uV3EkI6VvR4jMEodC3XrfrEy5ILSY/pMoj3ft2q/R/Q=,tag:JbXt0xSfhJm072tfHRbjdA==,type:str]
    OTP_SECRET: ENC[AES256_GCM,data:yRZP1LKy7+HZ,iv:zXrxlNK6/N0Nm6Jo7UzCrR4huwxz5eKDQuY4vou348E=,tag:tuc5Np1fc0H96sN8jOS2jg==,type:str]
    OAUTH_ISSUER_BASEURL: ENC[AES256_GCM,data:A3aosYTDyfcS8Je8tJg8zLNXzfzAhpiiX8XBqqYfFvdUhdw=,iv:/K2yFuydyDOqDSDpbaBJmIMkfBYBZ9wMC64tpBjRtmA=,tag:hyQPhEyFwDPsPKBld0mQUg==,type:str]
    OAUTH_DOMAIN: ENC[AES256_GCM,data:pqjKkXzQ/luyiC/dZc+Or2itBEYIYu1tixq3,iv:nUdrVQRyXhT/r6xod68H2HRcH3t5tcnJIWf8OTl5/G8=,tag:juOXd6m/7wySsyauTVfyDw==,type:str]
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:77eb3tRCq3Pdrc7EbrXsql3U9eRBSjQvNxHIutbHEI0=,iv:3rQIpEX3wIUrF5k7n7/sndgR9xvTzIr/ryl4gUfxFQM=,tag:BrM+Ecg6lbaEqriQvwXqSQ==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:YGSw0WTSNG9CQPce2xntVOmmMLt3AeX5KtBMsaymVXgKD1Ms0F27l84QDt/5tdF8U5pKpNpPBISHkBLMJPSXTA==,iv:BBRtOjgBNLmRzel/a2SU43FXyKLhbhWGa+S5Us8Qh6Q=,tag:f1BY1mVRCQdjJTAUNYKnGA==,type:str]
    OAUTH_AUDIENCE: ENC[AES256_GCM,data:dBQTGLdbqVnCENq4zHyJdR/pVtDbQPV+TBfrm24tDQ==,iv:66vX6kUI2Z625tAaVJWZ5p6TJg/Td8WmptEUH3p0fj8=,tag:bYqsAyvPul4+RYEdO7a4zg==,type:str]
    OAUTH_SCOPE: ENC[AES256_GCM,data:AfgDBwNbhWYayz14kanaXg9oEe8=,iv:qYt+GF1UbPqPGFZu6Q/IsCBKHmCaE611k/Tk6Kcny7U=,tag:c2M84f4gpBdocLuIEtOpvQ==,type:str]
    OAUTH_TOKEN_SIGNING_ALGORITHM: ENC[AES256_GCM,data:Rq0gkcU=,iv:a7g0f1BX7h6Nhhr8MS/WK/jj2TmWzrG88J/kO2OgyCs=,tag:LrM2Y117ZnYcAGbLfY9AGg==,type:str]
sops:
    age:
        - recipient: age1vgjwad52rqd29uyukq4nzsqp09z6e40a6zr7enhrv8psd4wnwu3qlfc803
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSzJUSTAxL24rbDB2d3BH
            Q0tldXZmdC9IL05oRTVsUnpGaEhqYzZqcEU0CmUzbWVtRlNUM0szLzJpSWRqMllu
            dTJSc1FiN2h3NUsxQWpSSjVScWFGVEUKLS0tIFBMRnRFQlNraE41VmZuUC9kYVVn
            T2ZheEJrVjlEVCs2MDdmQ2pMM091TDQKHr8UP5IPa0n/yMQO0/4aNUpyGLu1fYig
            Sl8n/+3D1bE4+4qeVdvt+V1obGYMeUUZEtkXm5xtm+i3f02bk2NLUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-21T15:03:53Z"
    mac: ENC[AES256_GCM,data:5kDGlfBRIpPAAL7mmP2n7HggLG98+55UjU6BQaOo7vhM5zL3x5ZCJyKFZynl05tHwnyDwIyxC64xz5K7jix14eGugb8ZKTo/3OzBlBPsv3e02CsDBWWQCLd/5atKSCH+LEFXuwJr/m7W5GgjOc4muBTWD0u5xRwAwoG9AuDBxkI=,iv:bDH4Uko8mgIrldqNgY6I7vlL4H0b6AdP8Kmb5KOJt3g=,tag:RqoqEmQKrfLs74FHyz4mRw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
