apiVersion: v1
kind: Secret
metadata:
    name: api-env
    namespace: gta-dev
type: Opaque
stringData:
    PORT: ENC[AES256_GCM,data:F4n/Ig==,iv:8XplXe2mOhaNySleryhfeX5orLfGNgJl0EXDscr5wFc=,tag:ff27amXYuEgRGnr9l9Qs7Q==,type:str]
    MONGO_URL: ENC[AES256_GCM,data:zxjP84h96UovFtuu5dInyvhLZhzt/AmlzXW/M9bE1i/Av2uXjI3+F0WDtrglSJxSX6uHVfTb8yO4jIP3treVIsOzFQrbpcFsiW+uySosFPFlAxjV4rI0tPNB7wHY0Q==,iv:o+yHc5iodUOClKqWoPcqJPqrrPswV5gVYZYabf1wNG4=,tag:std1Cl1WUBxM2RYjsfnBcw==,type:str]
    JWT_AUDIENCE: ENC[AES256_GCM,data:wHhkJWoy+O4RKKkJI64EnsSveg==,iv:eDv9Ca0Iv97LPePAPxD9jkfUaJMAS8UrdtkNJTvmnSk=,tag:wU8M97zegFkluWKxji8BXw==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:TgNNIE+TyVFE,iv:Ue7jTOKyyYRC4L/c6v0Msj3WpYeJmtivqv9JbXiUnGw=,tag:PHysHT6vvn3eroEpl2mhyg==,type:str]
    MAILER_HOST: ENC[AES256_GCM,data:VIL9sm8rrd+1CblLnKwpA9ocjyY1zJbB,iv:P31YIsv8miSdOhJh/y4vSxowGPjRHov0nboCppVLnVQ=,tag:NtiQNetsJGybmS7gVUlbjw==,type:str]
    MAILER_PORT: ENC[AES256_GCM,data:VuhlBg==,iv:wIIGkpQn8t+9rAfUWFbrBjm6S5+MjRVzyH9RCV3ZJG0=,tag:MnguiU2woruHHmn8rqBRfg==,type:str]
    MAILER_USERNAME: ENC[AES256_GCM,data:tBUd5FEYX0rdmVnvQmI=,iv:s5wa0STaC9gTOqButvBDqUJEhTsi5fTGGWT7aBqwmDI=,tag:l+ccnag0cAMbPbl53sNqUA==,type:str]
    MAILER_PASSWORD: ENC[AES256_GCM,data:DpFY1FutwhOo1l9oN/4=,iv:Q/C2whxqGscTpU4kVsxtNzj4dW6NkRGY4kKHvfmKgE4=,tag:ANhnS17yhcLb3a0yk6C/og==,type:str]
    OTP_SECRET: ENC[AES256_GCM,data:11ZQmkz9zXTU,iv:/2yXAD6hh/g/e9g5uOCQSnUjnpEbFIAhj0JekEbtY4g=,tag:q8W3vXWBFK694vFEquT+AQ==,type:str]
    OAUTH_ISSUER_BASEURL: ENC[AES256_GCM,data:YR08g5buFL4cL714WeL7pS0kUAsTgg8gRFRqAyxY85EkACY=,iv:ncu6nS/WsCjZ2Qrg0x/dK6o6tg/2O3vwgqaRz+DA3JM=,tag:ddrnUrVU6T9jYlMzeKZYSw==,type:str]
    OAUTH_DOMAIN: ENC[AES256_GCM,data:9HxIO6lS2xYLoxmZsZYK7FN3xNk1Nko9nd5H,iv:44/byRKd/I+1wrEKcRI8c2g9R4rm3MjCB/QTLFky//M=,tag:T0OPMw8CgWF9NnM4nc19JQ==,type:str]
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:tzx3MOG1wE5BLeH0fnNsvB52UU2HfH2zDDtDDSJEDW8=,iv:EF15lcYRBD1imTFvteoIy8zl7stmzdMGJ2iqeAvHNl4=,tag:MVyglywfVWeERFMt3kMgdw==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:G10KVzVWNex2PMGUKU4N0AyYeo+E00x43ktxOr0JNgHACO7RMJyvT2g/GdPmnyxHZnKp9HxTtHk3KQo9wtXTQA==,iv:QRRdPQWyWNw+6vUWydBOI6CshHxt8bv8poGl5NqMQeg=,tag:awmcMUsN3jPUI1rl0eBpfg==,type:str]
    OAUTH_AUDIENCE: ENC[AES256_GCM,data:fXd8NKM7Wjfhk7wVN+7SISD4YIKaBBVqGPR1frYuQw==,iv:kR80Hd0YGGd5lOx1fCCpLD4lX+z9mGpeS5i5Y1sHWdY=,tag:5TW4fC67XIzpx8u63Ul7tA==,type:str]
    OAUTH_SCOPE: ENC[AES256_GCM,data:7tgz39urZ/02QR1VYU2bdYVrjsI=,iv:RKvKXtS0XXilAqdwmPvb24wyZkQL1afnBxWo9QACTs8=,tag:sLYI/P9T82iDWO4uRRDDmA==,type:str]
    OAUTH_TOKEN_SIGNING_ALGORITHM: ENC[AES256_GCM,data:+z1f/jM=,iv:BDUdQHD9/0tdy0S1rLInCTfbFyHRa+/A7gHIukjV0uU=,tag:rDa12JzFwa6RdWgFP45UPw==,type:str]
sops:
    age:
        - recipient: age1tryrjtpz890ms9p0t0j4g36e8slteaunk92qnxf95puqz58aqe4qqgd4ea
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZenpOdkpNNW1JWUVhVWg1
            V2ZwcmEvalhTV25XZ1gwOFMzZURkUkVxK0VJCmVYNUgxYkNibko0TUFheWgzbkJS
            RUVjNkxadjFHZ2dDVEJkVzQ4UkV4b2sKLS0tIDBpUGxKNWNHd28zaHFyWStBanQ2
            VktpM2JXY3BXSE44aFdHRnFaN04vdVUK7t8FWeHogEQ6alPq90a05cjSraWNFLMP
            yA0NWrDFT06mHi4dDr6NbTBRBKYBLDDKiKCU70qMFB5EkxCsWkqfSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T22:48:42Z"
    mac: ENC[AES256_GCM,data:vxiTJyqiUbmNfb37PD7ZamYWlX3s9RiEloCvOlCqzGnSV53aiYW7saZElEE2cYOn8VTqbeyUstPJxuUVmsyaeTIMXr259x3yKbAi68vM/1Kes7UI2Ku0HKsVrlVKmDleRPmI18zwk30PlwRRCKSdpvjeJB9X7Km+vQYKrM48Nvk=,iv:LDqZw7JSUt2aOJbA6R0x3Sgo1ZyJvMkQIawWh8yilrE=,tag:0bYUHQQJ4HAnQ+rFN3jGXw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
