apiVersion: v1
kind: Secret
metadata:
    name: geo-trails-api-env
    namespace: geo-trails-api-development
type: Opaque
stringData:
    PORT: ENC[AES256_GCM,data:6T3kwQ==,iv:T2ZR9SSHz7V6lnVdHWnM+PXGFUiw1FcRz+qdhFfTWUQ=,tag:vAqYbHAb7Q8FGvrv3NBPmA==,type:str]
    MONGO_URL: ENC[AES256_GCM,data:5ICejXrleYJSzKLFLWPKJail69rHU8bwFrzZSF8nF2UMncguIZljkU6JnoUbIryKuptVagDfrotWgXMaIyCFFOCf8d6QKu7yEsgi/yLyDpNN0U9YBSS91YdFRHdBRQ==,iv:ToiNaoPk8UbMg0EX8QHno7rlKhE36+RZ2u+c+ayz/Tc=,tag:BbQFkPdi/tgUw4B0Qeu9wg==,type:str]
    JWT_AUDIENCE: ENC[AES256_GCM,data:uu7spiO98d5U0tT20RQVhZPotw==,iv:rQjsrC4tP1UfRoMx/NA3eDYX387N8p9WLt2b7PSmquM=,tag:yfyeFfjNOzmrizKJfQXpmg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:n+vCcL+OErFt,iv:TQx83rm1jpyvMAkVmMa9vTlKwmI8DBVwGzJkHqZZf3E=,tag:xO6SR5cYhnFcQlZZv3hAQA==,type:str]
    MAILER_HOST: ENC[AES256_GCM,data:zUvqU97uGeoOt9277rl8RJcjFZPtAk3p,iv:689bosDElqyxnCxHtnkb6xal6Mw5nx9096C9HbCVpuY=,tag:hbLlndm/oOiZrpUE4ick8w==,type:str]
    MAILER_PORT: ENC[AES256_GCM,data:78I+Lg==,iv:TmGRVvgO6YbR/OseMYpbKGGRIcNwYrVFSnDLi0M8vu0=,tag:QkAxwqRF9A5XmC+JlIWldQ==,type:str]
    MAILER_USERNAME: ENC[AES256_GCM,data:tlXCUD/vDZ/Blnfg4ZI=,iv:TxJ2ULPGJqfLsadz2yg7TVxE795Q2qNCzuVDJTClctU=,tag:UlqJDh3O5BlxgXwwrld0JA==,type:str]
    MAILER_PASSWORD: ENC[AES256_GCM,data:M7MaVG16JS0OI2q1ZxM=,iv:VfFdN00G77AF/xXnLWH0XmYIvXMEC6p3QNmjcoXlkz8=,tag:WKvmySsAxMiTlyf48PzpPg==,type:str]
    OTP_SECRET: ENC[AES256_GCM,data:Ne9G7UqjzPIc,iv:jv7gkoqr32z8HdKNB9qMcsXEQMqmdOENHtWTFHQOjIU=,tag:aymdU8Vjta5y+j2njQf6Hg==,type:str]
sops:
    age:
        - recipient: age1zc4vlxf4wk3h8g6a09k4e0sq89966dxww8pr4v5k44xh862l3qvss4sw0x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSWxZYlQ1RXdtUGloQ01n
            VHA4YzdEaGE0ajJhZzhZNUlnQ0puUUV4Q0hBCkMrc2JRdXlTVGthUWNyd0tmZ1Rz
            b29Ranhqck4rTkxTcGIxWlF6eEM3Q3cKLS0tIFZSeExXNlplaHIvc082V1JGVzAw
            cWN6QUYrZWFYOVR4U3BLWG5kRmZuYUkKWDsQgAzlDEdYvIvULiaQCCCOKoPTrGlJ
            4rqWN3CJ5MbLV+eAYcRcLUogH8ce3UokAsyXdwbjU+FlIMcaO6WDuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-06T22:33:13Z"
    mac: ENC[AES256_GCM,data:7k4YFbG41NrE7CnnyWUL+bBDJr9eL7e/N0rRvcRm7nJU95L0m1D6KSD7rxf3USHwGGCAmq6icZ2pMGvkES3vCBUusosmi6rAuN3ZmHL860QdFRz/rJeDpi86SFBpdTupX7fGHqPXM1HDniHO8/tX1ie0i8WnO6WOxVWOhzp7QDE=,iv:I1iLZSqwgq1UbwzTs5XJ3CDVYd5nis/jKsk70spzVlo=,tag:VT4dfQqd99jVzfIC5B8nlw==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
