apiVersion: v1
kind: Secret
metadata:
    name: geo-trails-api-env
    namespace: geo-trails-api-development
type: Opaque
stringData:
    PORT: ENC[AES256_GCM,data:XQ7Uzw==,iv:25P/ilBlrHsMAxiTz//aW9zdNPbWFG+rhoi8RQqjB4Q=,tag:zHHRlskOwFpC9BtI1uRERQ==,type:str]
    MONGO_URL: ENC[AES256_GCM,data:dTdi5BNvx4Q37eFbEsKUJ6Y+zT11wUzDhR1tOAhbSp3dNTBZLt+AeaVikaSZ,iv:Ng7+ArvmNsWzf+Ubq8OrrjxTS0opJbVdjlsh21nHSfY=,tag:+M81mSVmHnGIfuDNMDtkbA==,type:str]
    JWT_AUDIENCE: ENC[AES256_GCM,data:SPr9Ms2HplHEc69rJIOxnwKpvw==,iv:HwMJK/KjAWpG9SpgNiJq9UYs+llwAc9ND85IUPoBVH0=,tag:nflwEWuE+OYMBByvJ5HULQ==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:lQSbqQ+5DzN5,iv:JsmNB3KFjpeZHRWDeGRy7HonDqgUAF5TYq52p7Uc47E=,tag:UQSCqqiO31BRuIwU6gufeg==,type:str]
    MAILER_HOST: ENC[AES256_GCM,data:gVzXJqcjcxxxgxC3mrSvoqw6RIQ+R+gX,iv:/dpbpA0uw0FgGtvrtleL499YSGSSuqdEP7YdXob96eo=,tag:NfN4RP6wKPLiITYGcTm+UA==,type:str]
    MAILER_PORT: ENC[AES256_GCM,data:62k4ow==,iv:qprYGHWiqV6yqOJySvlhKtynC2DZCB0prswmHCT0yzo=,tag:N3Hb73bW6ou9LW7VHmMhoQ==,type:str]
    MAILER_USERNAME: ENC[AES256_GCM,data:/9PcWGT12m+PzWLj3Dk=,iv:roUyG/nVVjcJJ3bOnKJoNdxL4XEopSwDPwYGJP2/hgM=,tag:UL/AXNu1el15MUX/yVN8cA==,type:str]
    MAILER_PASSWORD: ENC[AES256_GCM,data:MB1Z46ZYHA47sMnyRys=,iv:KoGonykT1OKzDRsRdZ4fWD3Ccw8F8KbdXcXrMWrg9c4=,tag:ciI9Q3+UARzJB5KBYvPDxw==,type:str]
    OTP_SECRET: ENC[AES256_GCM,data:b+zzGaKgSZ7M,iv:q0mUW7YxsnT7rZpSNtL3m7K981n+oJZdREK0zwRDQc4=,tag:VrX9J8DFM6VfvSco5ObBvg==,type:str]
sops:
    age:
        - recipient: age1zc4vlxf4wk3h8g6a09k4e0sq89966dxww8pr4v5k44xh862l3qvss4sw0x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxT2hXUFQwYkdIb1hRQjZW
            WDdTQkllOHNkMDlMMHowSU4xaVRqdG45dnpJCkFCc003QjcrQktGampFcTJTSjlE
            Vnh4RW1qNHdrK3pTeVJXbEozTUNBT0UKLS0tIGJZR0NNZVNRQTVHTEVQTVVNMk9n
            R3F5cm5jbHVycUo0VGUxNnczcG9qRkEKOdHathylLcKaQ50FyN8iUKZRDFK6eQQ6
            rnlPZKACkUt2nOCwZxDvbnYYeDRLjYdMRkFnL2hMZWeBI7TGhLbneA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-06T19:13:26Z"
    mac: ENC[AES256_GCM,data:vG3ioS1cGiCDhD7mb6xaQDP9rE5rv7gAV7uvb49AHxpq6w7xV6C3RzEDhZAMjb6iciVC6EC6QHjfT/+hPMAVaZKVDvJLoE+CpGl8Tude4riEj/VFtP3fLbbffqV34K2y/m80fpzUZxubYBIEUles+iZfFiUMFJB4eULTRLiHECc=,iv:Dpty/5Rqx/+jSoUgb1JkjgGkLvolO+2e7L9/I1qQj4Y=,tag:fylKyP6ihFSD3RzBq0qGIw==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
