apiVersion: v1
kind: Secret
data:
    .dockerconfigjson: ENC[AES256_GCM,data:3lWDJaoZFgPiBKu+wbuwn4A5EmyrKL+33TUE3jj7h7Ds0/6FE64/8A==,iv:pDZFJv1RCi2KKWMLKzQz+rTLJLGYbSG9eqqJvx+Vlbo=,tag:YrixyFvc3j0yuTgBKfuBTw==,type:str]
metadata:
    name: ghcr-token
    namespace: gta-prod
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age1vgjwad52rqd29uyukq4nzsqp09z6e40a6zr7enhrv8psd4wnwu3qlfc803
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvazM4NU9URnJQejNHQ1Rp
            MDhqNkZDcDJGZDVzUU5aRmk3US82VFRldVFjClR3VWxhbXhBR3ROMk5jNmJYanhH
            K0xDaVYrZFdnTk5xTlNJUm1VYjdyOGMKLS0tIEw5cTNUWFUwWUsvMWRnRXFDekh2
            a2RNWTFTMFFmaldkeTZyNDUzYVFIM2cKYjh4GVCz+B/Py1nDN4NUowDr/EO9cYIu
            DjXlmenJULhUWxnzjNc8Vx+/NkTWT69aekZemyRShDt50y2InQd0tg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-21T00:42:29Z"
    mac: ENC[AES256_GCM,data:1OOQhloKD7NTuzXO7G7dW3Ll15lz3ErNMukMchSbsUGa63R3Ws/A4UCxKe6qPiAH+JTT8qoLvx7/Ot3IdPJYrKNO3Rjlv8P0po5gGjzEIefcUzO0JxKTSh/+RWbb5dIh9FDwVhlKnqd3p3aGFTui2OxRrP4IjFj3c1PzPF/vj+g=,iv:shzbKqv72fQNBh1YiazD+a8I5J0qBF8zedPQmujPa7g=,tag:CsokvQ9k7LUv5ggp1/YFyQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
