apiVersion: v1
kind: Secret
data:
    .dockerconfigjson: ENC[AES256_GCM,data:MfOInVN8rX64iwYMi0ciIkwGc2HHHogRyspghczQyiiyioT0sIjF53dscZQMyNouQYq3muQkAA2/JLufSo6iCQE1AeDkFoIeBIecTeFaQ81NFMlSJSzmVRC3mpMnagyaQxi5d2gmBMOFLMtXzw6EvxJ0KI7PtPOMGuHQqpUaiM7e8CAG4mJtIcm+bg27k/fvUrFw3U15rQiQk39iQA4AT3C5raeUFv20tx9xROY8FS4Lr9uqHYgcNh1CODIrfifaxC75dVGxijuENt6Gp8WXtPknfwT7+tqCcxb0/LNNGUFhntnCQ7hKsdVpvXJy0IE9yGm9wR0rVNKXBMEN5sjC6Ht9lYFdjTDTnQr1HXoLPlDRQlRFmye1kw==,iv:7Rhv44EZerkqkKMjz2aRg1+OTy9wI8PJdhpLILiM/eM=,tag:IXG/IKQ1tCqFNoLC+zzKyw==,type:str]
metadata:
    name: ghcr-token
    namespace: gta-prod
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age1tryrjtpz890ms9p0t0j4g36e8slteaunk92qnxf95puqz58aqe4qqgd4ea
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSdTVIc0d2M1JSdXhWZGdB
            Rm0wMXNFWHozT2pxaWt6YW9DMWNmZ3JuYm4wCitySGMrMmpjbVVKenlMa09Gdk11
            V3lWYjVQMFh2V01Rd04ydHVnTUpYQzQKLS0tIFNWNDlSZERSUjNWektMZlFhN1pV
            VlZRRUJ4SE5lajJkZHdXVW1XbnhHeVkK4P49WPNEsGaMvKjojqpdaJDByAkqrnby
            opf0eGB7NCkkV0QXlXnMxuNlVWAerSvAzwWVMb/cn9xh5ycPLzcnOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T21:02:29Z"
    mac: ENC[AES256_GCM,data:GZsgYZzrVoQUFzhtlisLaC501OmZi42qIeu2h87Jf6BjFQu8H11SDUR/VAq0esym0Fri7EHV3i7qj3rBxXBGPJ9QoTgtoHWSGObf3p8s2jptiunfeyjrHlJ2mWnAFoYqmrcqw0H4oj4L3tJTGKvmmg2vsdZia6+nZomDn99O/RQ=,iv:asPkimhj46hHSyLN8Rcshppawd/1XzPOA8T6yVhdrYE=,tag:v5IpJjruEipiA97pViNsAw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
