apiVersion: v1
kind: Secret
data:
    .dockerconfigjson: ENC[AES256_GCM,data:olhdDF24H89gVqD70j+lSvhKTKZIo/duLbfVhk+kiWUD+nRyG84SGzli4X14U0Y+a8oj2qeGbgDom+tG5g0ZgTuBVLLf7YhYnXVzBdO63T+oWZy0nn6wRxQWz43YZkRW/ipUzXdh+CUbnK2FT1VOGT+lIDFpj8dJbStiAkeOrHe0tX+AwITUDtfSYch36Dnja8LwiK2VD9Z1OUCnEoxdNODTyFWuEbYjHpBXoTGhbWCNYeIgxcfSWPu0W+Tsi0W6W9NlIrjI5TvwKcjV4gDroU+8BGxv67Hq2BMs92UU2w/gF3DT19VyPr2RgDfCJpWec4H9juCiByryr8u93RbDKDWljYkqzlBbYucQW8A469aGgWW4uEmkmQ==,iv:ha1w4pO8XZ0HHEg3/5dDZLWtYcO7LIQzVjHN1I5J1/g=,tag:OeK6omuyA1KtoaFt+bQTYg==,type:str]
metadata:
    name: ghcr-token
    namespace: gta-prod
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age1tryrjtpz890ms9p0t0j4g36e8slteaunk92qnxf95puqz58aqe4qqgd4ea
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZ2tRbUxBTzdlaHJqWXdO
            QUtJSHJYVGNMZjVScGNGNVFkTWYrcDMwWDNFCkMzbi9wNXJ3OEFMQjlqeGorc2Q3
            dmd6RXIxYi9OdFBGSzBxUVlaZ0hSQTQKLS0tIHJsRW1HKzJ4OVhRMUNoam5vUFRG
            b1lvRDYzVnVNdXNjU2t4YXZFLzk1VFUKqx6djmNhMf5CMhpHlm1EWOrjjX1BQlpv
            YZKO/MmIfseu8nYRWgUsJTPyzQBSHTDoGv4+r34yd9X9jYFgIpKCqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T22:48:42Z"
    mac: ENC[AES256_GCM,data:H3v1uUq1IRsFIEefR7fMQeIPfwk6RW5vQ+cd8AhDaG0EIqQfTPfiPyVjlzs0D9xltf6G7IqhxE/bOkM1rT+uSu+wgBHfze33/kdNM1GrmGGFFpmTlWfzRAvAZMJDtbaatMHiOsZHQjrgIWn/+ht2VjabL/ifgD99bBCfYVnyZI4=,iv:GF1Xq21b3NjDHjvNAQNaYMI02L8K+vZkTVmFKp5IGM8=,tag:BSxlkgdDmJ48Jk2ruirwmQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
