apiVersion: v1
kind: Secret
metadata:
    name: api-env
    namespace: gta-prod
type: Opaque
stringData:
    PORT: ENC[AES256_GCM,data:CohUTA==,iv:vhMBvhU6Qs31MfEdBH+JnSOB/bPyKFOaFypv0Se/YJI=,tag:i3x3bqlft+yK1BmEqSE+Rw==,type:str]
    MONGO_URL: ENC[AES256_GCM,data:hjHeL9LdUI4teY/d2RWjCncxZ5mhfiDLZBiKV62bKEJWCLgwAW5fPt7eeYDrxBYOkhpqqmrQu0orC2UiDvKC9+59MaF4q/x+lqE0O+htdA8vV91V+LqAqfzkQxX9kg==,iv:5OXLk0j57vvf9yL6tC99ZelcNsFbM/0pRjf8ATqO4Gs=,tag:k9zb9ry/eRTw526UfkdCzg==,type:str]
    JWT_AUDIENCE: ENC[AES256_GCM,data:Qm3lhOVAsaqO2Rxp3v1R24PnLA==,iv:d68squjqSEMWLg3Nb8wSh74Nb9EsCV/07Yfq+uez4FA=,tag:ss/IKZqbqvmu7G/IYEpIFw==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:+5t5Nk83srHe,iv:e9lrJxRHYM+2CnQ7gG5SB53zrpiKRVZnxwCJ6xTCvLs=,tag:dpR8JJGJcLN0yh0kijSFPQ==,type:str]
    MAILER_HOST: ENC[AES256_GCM,data:HMa/x0FcT01nlRGtZfObKAs1Mos93mhM,iv:X8jAa5uWXTsyItoDuTq6wc5FmDRxWQQJwn1EZqn07Uo=,tag:HMNUA/fKnAFnT28mhRYJ+A==,type:str]
    MAILER_PORT: ENC[AES256_GCM,data:S9rrxg==,iv:VafZa0X4jBbWOATsgc5dSd4EbPzAKzE1DDJTxKkTiqA=,tag:zMbmvEgVJ1awoREiL+Pihw==,type:str]
    MAILER_USERNAME: ENC[AES256_GCM,data:uOKcHXYoYfDiixcYR4s=,iv:uVfE7ETC1u6UBw3M33OoLwNTWqE+Do+74J8MmAOtcWc=,tag:RYGLHZeECiSHJvFoTSmWCA==,type:str]
    MAILER_PASSWORD: ENC[AES256_GCM,data:/NpjUVBl0dQ54XXGz/A=,iv:YW9IfQSi/8zvtzwRH9T+516lgWAU+gkiWqhhT5zbpWc=,tag:BC3kLjtzJu8skxRTGslkvQ==,type:str]
    OTP_SECRET: ENC[AES256_GCM,data:fn3BFS+Z+3SY,iv:qHJ0uoIgo8OG2taM1e/wljRfE8GrzBfirkersG55Ew8=,tag:yLHJmbwoUMihk2dUudi/Yg==,type:str]
    OAUTH_ISSUER_BASEURL: ENC[AES256_GCM,data:1Hg4LxecFvwbgKNo0aMLyogNllQV/HoToeE0rxYHy7vjq/0=,iv:vRAus/EHuZzsVI+9CywLLeyGrcna0kbTvbSoM5ISQY8=,tag:XvS4XoCztUPyFEu53/bHFA==,type:str]
    OAUTH_DOMAIN: ENC[AES256_GCM,data:E1CJaLoKltHkMThE0NmrodiOsi2Wm+kDNEH1,iv:qkl6b8utELNSadctEyooDUCEduFhF1Q1vGODfUfMgdg=,tag:AX1/v0WWaHmbqxgfjdJmmQ==,type:str]
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:UAJkI0loIfNJ7psNip1LXdpYVKCaWiAO1/4u0a6KIJc=,iv:9vYb254Q9E4DBcBXNmnABn+BLhPBzVSwQEAGec8y9dc=,tag:B8QsQZwlGQbBGeCh+por3A==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:cuVCew15nNN763//XBwtx3iBCPHH/k8hJvxFIFeLM5w0xoulFUClX/3DQC/nAR8AGkoRwr4Or5tnThC7hz99aw==,iv:7cBAdEpSWYk3NdIsLc0rleAJf16KOOvDg5W50wJGPdA=,tag:NCcpka/eWCs6qwvQ9cv1+w==,type:str]
    OAUTH_AUDIENCE: ENC[AES256_GCM,data:H49aXKNgsgDzQIyQhKnGNT9esxh855CVM0sADSt0Eg==,iv:TI5tizZkAL5zPH5xpBs9lAlDNVqQcHi28Ib1Ykla4DQ=,tag:UnacocsRIsA8zWlv5HkfZg==,type:str]
    OAUTH_SCOPE: ENC[AES256_GCM,data:ACC5LRcbYgL0oSyvTARbgRAA8e8=,iv:QvM23rhpY7p4JB+5KpAzftLS9pEMbcNCjIdk2R/Uwhg=,tag:V5qm5iFqbYLLJp4MJBwzRA==,type:str]
    OAUTH_TOKEN_SIGNING_ALGORITHM: ENC[AES256_GCM,data:gTSb0Cw=,iv:pOSHOypmqQd5L85bp7Q+NEYs40mcE4SecVeufUhe3cM=,tag:LSse7T+ProiR+afMzPRqqA==,type:str]
sops:
    age:
        - recipient: age1tryrjtpz890ms9p0t0j4g36e8slteaunk92qnxf95puqz58aqe4qqgd4ea
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqSGtDd01tTjdqTyt5YzF6
            U3ZVRXQyY1VkVDVTOFRGYk94am45dGlvMFc4CndILzNQWlh0ZXZlVkFxcy9TbFFR
            UkRXd0o4SEFuYlMzZE55c0FLSTdOVGMKLS0tIG90bjRoWmsxdG0vTnYvT2ZpM21i
            RU8vdE0yRkhtbVFWdkF2aVp1clczWUUKq8rrh5b3yQDo4ycPE0BwEiMIEnZ6N0H/
            wuOXMGzcwcAKBLrVLPtwzShTd8YNq3fkOOH9QSqCKVttwjZGuol5lQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T22:48:42Z"
    mac: ENC[AES256_GCM,data:Jth2gmEmREyRgG5Sw2iZ7DwPe0ETfD4oW5ydXBTI1o6IAtNiyTBd8bx+c6321Q/vTj/SUpBeG2YnFN6YVdcZNM+D2VD92LWEVz5zidLtM8YRwBOlCSLxqnTgiZ5i3nXLvdX0iP4bUNhhpa24NUp2o58Imrsm+g3/3qW2A80Mcec=,iv:cQgZrCEbb4XPt8z9YXgoB5GAMIeUtSFaK5kmup9CEno=,tag:0MSlckYztI6TetBOEAozWA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
