apiVersion: ENC[AES256_GCM,data:m8c=,iv:EpgHwgSPHWzyaHN29+4EEu7z5DKDw+cgg1RAEGYObNk=,tag:NUEIfzBbTsFFF0mAfzSW0w==,type:str]
kind: ENC[AES256_GCM,data:Tn3PLeyZ,iv:cnkZHc/FtcckTs0Qmc9Oyh3E35xPLklnhHmatF92VU4=,tag:2XKo4tSswJ7WCu2g4sbeFw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:uabnU9yavw==,iv:DoRtlBc9k640INmO8V4CElwKdFpegE+Ogf7qHqeYRyM=,tag:Es/eJx82YIhfJCe0j45dYQ==,type:str]
    namespace: ENC[AES256_GCM,data:L9iFGs/fAdA=,iv:ToE1MJfCyIPvPT5wQFkONWG+qKYlSXXgwYOH0m5t0Sw=,tag:riWJnOblUsiu6GkmqfgoLg==,type:str]
type: ENC[AES256_GCM,data:JnKzgRwc,iv:TpW9/OIcdEZcSNhogpaO4PTs8GGc3ZTqxY7Esd3eURc=,tag:FP2sYqBfrJ8TW4NppsKimg==,type:str]
stringData:
    PORT: ENC[AES256_GCM,data:5mWfiA==,iv:LMfU7l7CLghl/FVAKr+9thKEAAL24ZwHj4+Sb/VY77Y=,tag:2DA7n24Ds4RMqfnPwx/PLQ==,type:str]
    MONGO_URL: ENC[AES256_GCM,data:Rb3YrV37K6ht4SpTlazR4KBbcI/M7ln3ADSKURbm0z6dxFgwtxD3PrDaFLs14u0MvUjlTn8wMnPz4dAakQZz5KSX3STqRInsI9HFtlJUMPUBHeRq6HcmEbo/yutHtg==,iv:MxfS7UuNdbl1DF5PiKWoEy11z325n3bxMHmiKvaFN3s=,tag:SgONEccbCSUcwJ+NhNa20Q==,type:str]
    JWT_AUDIENCE: ENC[AES256_GCM,data:1BDj/oO8kM57hQ/yCo5CWOMgrg==,iv:IKfYDynimp2f7xEPb1+7t+s5YA4AtHLq6v8CQo85ddw=,tag:zFE+75R7jNESmN8eOMNp1A==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:/6Q6SElKT4lA,iv:kvsUVgt5nQySSIgSYk5LgS5k1AUimPQX/jlFDcE/uHE=,tag:U7jOSTI3E2OhsLYX0Da+ZA==,type:str]
    MAILER_HOST: ENC[AES256_GCM,data:ZXhNn6U5BQb7QIQjqXU+7Lj5eYNlHQ0/,iv:a6z7Bst7+tfq7yXTS3lkSBTJA6IMrsqiSsFw+tMKghU=,tag:TaoZhaymZ0+ax3CahlyzGA==,type:str]
    MAILER_PORT: ENC[AES256_GCM,data:wuLNhQ==,iv:B9CQOLX3CImpvELL2tT9k1oHualluwpHyN54dgNlihw=,tag:LfgF4pv8vnTJ3dlfqZfiIw==,type:str]
    MAILER_USERNAME: ENC[AES256_GCM,data:d0KOCXLfNf70CsVPNlM=,iv:5B44okCAL7FRbdo+wa+UNzeYH9P+sh9Tyqvc5Ppx8LI=,tag:Buv4UbZAFb67ERdce1e4Nw==,type:str]
    MAILER_PASSWORD: ENC[AES256_GCM,data:y2RPGOS9JuaEpKpr2PE=,iv:AT2cHLHDFm9sIpC66uFn3z+p7s6lSTZjo9MViGwOyjQ=,tag:w7088UKQInVWtznu/SzJBQ==,type:str]
    OTP_SECRET: ENC[AES256_GCM,data:plRa2+kzKlW3,iv:IijjfmVWiX1j7txJsJxY16ak1ZKVnZEhuguMfgTW9Z8=,tag:8W6V0IuakU+C5Mskv6Jvmw==,type:str]
sops:
    age:
        - recipient: age1tryrjtpz890ms9p0t0j4g36e8slteaunk92qnxf95puqz58aqe4qqgd4ea
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcmpMQUszUDM2UUtMWmhI
            bkxEMC9oU2J6MkJYMU9hSHh3U3FXYVdpY0I4ClZhaVlxSFhObkcvQmtmb2pQS3lH
            WnZIVGJkcjVvV2IrV3czRzNBcDlaZVEKLS0tIHhPelR6b2d0TzdXY1BtWWRtazlt
            SDloNk9VYWFUMlpydXkwUEVqams3NjgKdrery0sKMtsYrvQaHEgtWK+Dhl/Cefwd
            Uo3iwJKgZD5F6mcb7KatQpdS/Js0qG63bQr8pfefXciMSloRPAFw7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T14:52:47Z"
    mac: ENC[AES256_GCM,data:+kvFbgHgHKNMQXdgrdIuFQwTS16l2v+XuGX8fVFqs545Sd1qIm1UlnwcAXyy3GKP1RB7Bw7/nNuTh7AatK54dzVPG8Z9dk0ZgBeg7Qr5fxdWaUFlpgAexeEdVNBQGzyiorC+7CzwTLZvANpYUHD9bKq+KZvBCONLEPXKmkvRPXk=,iv:B/Ni6Lq5GWo1KFjkFVx5GhxE/JBipYsIqjjm0wrCk3E=,tag:a72yd/tXHtbAagl2JWJd7w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
