apiVersion: v1
kind: Secret
metadata:
    name: api-env
    namespace: gta-prod
type: Opaque
stringData:
    PORT: ENC[AES256_GCM,data:B1xiUQ==,iv:o3Buxu9oY4VqNGHO0dJNAyLpnSCg5/Z62Cj1+eQXfos=,tag:APfSi9/PvradMQqhfjzafA==,type:str]
    MONGO_URL: ENC[AES256_GCM,data:/jkagCjSN2QOSkuCyEZFHutNAW3Q3EWqo1Y/qlNmb1VwsnXoElXIa1s5Lr024X+nJv5g1BpjYhsHls8PKy7rFyzQsK+JVjDJrvipwFaYWRQqwBe1+AcVcYimPPNKwg==,iv:2gn/sxU9F/SjLac/piVDg92Aaq27I4D8dW8I6TPGxYE=,tag:ZGx9IwaRSdNaZrb8n+9Kbw==,type:str]
    JWT_AUDIENCE: ENC[AES256_GCM,data:C6snr25VezOrUzgNLLcji9fgig==,iv:bBOKPlbGmtgabQ+Xw6wuQvepAEZmgPDCkZ4pcds+3Ik=,tag:DPUo0Ebe04dcrtxo7YZkkQ==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:cxZp4XPAkbVi,iv:1XwwXPcM0cr5JfH2gEoRl7q72X0zQKE6/pOpwQTN0pw=,tag:NlC1XPobXhG9YMPAVWj0Nw==,type:str]
    MAILER_HOST: ENC[AES256_GCM,data:v0TUNKfvisX3h/HI8caCOcaI5TmopKN9,iv:Hdakb+ZrYweBL1kN25nWiTytXM/dFlNxjvWxZ8DHSzw=,tag:2wd48QKcj5N/HoOn8nv1Fg==,type:str]
    MAILER_PORT: ENC[AES256_GCM,data:aAQnHg==,iv:kQ/AWhO0RzZsZJ/1rWlr5/03F35QxEXSzh/DF1O40Yc=,tag:lGO3/Pfl1AdUERq8PNBbcQ==,type:str]
    MAILER_USERNAME: ENC[AES256_GCM,data:Zm3Ps40Xy+nrwGA9bUU=,iv:G7EIumVSpmzYO9OtAR3taks5FYmaxOPzbLE8D0g02lE=,tag:UZboKWrHiIiuE/iW1uGMdQ==,type:str]
    MAILER_PASSWORD: ENC[AES256_GCM,data:8lZ3vkGbXw16oGZUtC4=,iv:W2iPftLO8WvhVW8W9tebL0GE3wPLPp/O9jMjGHcZCLY=,tag:FwssWmmldzg0eaz6kJq95g==,type:str]
    OTP_SECRET: ENC[AES256_GCM,data:db+zOtorrN1B,iv:vmnoPha8bTFDQpENuz1n9bMQzAgcfQzCiNyLVyvhjUA=,tag:9khnIhmtbgEQFvN+RVFZaQ==,type:str]
    OAUTH_ISSUER_BASEURL: ENC[AES256_GCM,data:TpqV6gZYp7mzAYjk1HF7bPGIWltkiuM9OL2eKr/bB4GKMtQ=,iv:n4PXL3IQzku5xWFZeKvGK3XS2rS5bfEouLVh450EMsw=,tag:XbBKglnU7nmtlAP4mOeICg==,type:str]
    OAUTH_DOMAIN: ENC[AES256_GCM,data:41d/mu2eJpfn/hWW34l5O36GjAmpcXJW6Psd,iv:rKBhlFZtEUkCqbF1QLaDTq7JN5fZwaLROStOnEWhr8Q=,tag:Z4x2+CBu5eANuqBuepGDtA==,type:str]
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:cV6Ixc+wAWbKMaUgWLDfZ9nz0YoJ6s2gDROyEIuOW0o=,iv:QWH9jSPZJD1F7+sV+OxaKYE5HxnnshftLFw8575kaJQ=,tag:kXlQtP8wRNPMGJiONG9b5w==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:ozBZh/90HUZxuspvWuCM+p8hds59FDUw0m+KvfyYC5g6oVwto2mBu842pzrApOunnIdo0tkrrOc6NzPtzjWh6Q==,iv:r2POSt2pSMaKjhVSfQli+eUotzPrTXlSs7xlKz+ZyqQ=,tag:YUm2G1br2bsM4El8Tg6UUg==,type:str]
    OAUTH_AUDIENCE: ENC[AES256_GCM,data:Sd10nnvKUV0iInnzZ3QL2WUNBuWo+BHG0lWeBTV20A==,iv:BCmn9FDvsAlhJfcQaw5yQTnHBpGpK98Q+nfkVwyROvU=,tag:0QU3k9BKKQZVx8SLQfMZCA==,type:str]
    OAUTH_SCOPE: ENC[AES256_GCM,data:ps9/I1QuJa8LDRe+Y7/ESvlqYWs=,iv:WIzBPbQu49Joah6KILFgs5/VaZzdZbZbxgJw/v2tSu0=,tag:uUZ6hcDR8Vpwc1SuewqEbw==,type:str]
    OAUTH_TOKEN_SIGNING_ALGORITHM: ENC[AES256_GCM,data:L/+Oo5E=,iv:dB45hXffJfh8d0W02YFP5RWQJVcR4CGn+ciZ7CYzfuk=,tag:B+7JFVrjB+ztZs4JpGdfGQ==,type:str]
sops:
    age:
        - recipient: age1vgjwad52rqd29uyukq4nzsqp09z6e40a6zr7enhrv8psd4wnwu3qlfc803
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5c3JteTJvZ3p5SWdzSGxR
            TTR4QmlDZ3RZaG44RlR5aGgwcGl5TWNiY0VVCmFEYkRza2NtejdtM2Q5bk9tWitq
            YlUybGtZSVJSMUxsYUNQT1dDYmY0NzgKLS0tIGExeFBmN2JsakZLdGxwMGl6eFVS
            WEhGR2Z3M3cwempRTStkYW9FY3NMSlUKuziNPndMUoa6XtPsBRogGvGuiwfzatGV
            lSB06KveSh2Rlco8to4HJSACWSucecrTnNgbwytNLAu39de8HLnuBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-21T11:35:08Z"
    mac: ENC[AES256_GCM,data:9yp6PtIgd3O/qtkSZoLEzBhugO1+ogZNN4lWQOWwzVKhEk6KVw6u7KndSo+/GLTOTaWvHoxKBHZjRWp5bE7hSyMdycJl3DwZWJ4NaBglYmn9o8IJbrWki2WKbgj4MpzqSNmaPtdFR5mkOrQDqIDwIJiE8lnCnPXzUbUCOr7SF4k=,iv:yy5ebIGmZyatHpbUXRLz+0FWdfytISSxrhLDIXWeMZU=,tag:EXLqBpb18ljN5LxcoQe4sw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
